compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  zero3_init_flag: true
  deepspeed_config_file: deepspeed-config.json
  #offload_optimizer_device: cpu
  #offload_optimizer_pin_memory: true # Set this to boost throughput at cost of memory
  #offload_param_device: none
  #zero_stage: 3
  #train_batch_size: 16
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
# mixed_precision: bf16
num_machines: 1
num_processes: 6
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
gpu_ids: 0,1,3,4,5,6,7